### ISSUE TITLE
The generated file name is too long

### ISSUE THREAD

**Issue by xfh** [STAMP-project/pitest-descartes#104]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: HTML Report
- **Execution Environment**: Linux, EXT4

#### Description
I've been trying to run Descartes via the pitmp-maven-plugin, but it's crashing because the file name it tries to generate for an issue (pit-reports/DATE/issues/TESTCLASS/) is too long for my file system:

`addBelegung(ch.dvbern.kitascheduler.belegung.Belegung, ch.dvbern.kitascheduler.reporting.controlling.betreuungsvereinbarung.PlatzTypLegende, com.lowagie.text.Document, ch.dvbern.kitascheduler.pdfgenerator.PdfGeneratorContext, ch.dvbern.kitascheduler.kinderort.KinderOrtFraktion).html`

It would be nice, if there was a configuration option to specify the default package name, e.g. `ch.dvbern.kitascheduler` and then strip this path from the parameter names.
I think this would help keeping the file names at a reasonable length.

**Comment by oscarlvp** [comment]
@xfh thank you for reporting this issue. We will try another naming for the reports files. In the mean time, you could check the output of the `METHODS` reporter. `ISSUES` is in fact an `HTML` version of the `METHODS` report.

**Comment by oscarlvp** [comment]
Starting from  fa43f01 the `ISSUES` format generates one file per class. The name of the file is the name of the class. This should solve the issue.
