### ISSUE TITLE
Descartes reports NO_COVERAGE issues... on main() methods

### ISSUE THREAD

**Issue by gibello** [STAMP-project/pitest-descartes#110]
#### Characteristics
- **Issue Type**: test report
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: Descartes (tested using maven plugin)
- **Execution Environment**: Ubuntu Linux 18.04
- **Reporter**: Pierre-Yves Gibello, pyg@ow2.org

#### Description

Descartes reports NO_COVERAGE issue on main() method

#### Steps to reproduce

If a class under test has a main() method, Descartes empties it, then runs the tests suite.

As most test suites don't provide testMain() methods, you obtain a report that states that "main : All method instructions removed → NO_COVERAGE"

Maybe the main() method should be filtered out, and not tested by Descartes ?

**Comment by oscarlvp** [comment]
At most I think this should be an option that developers can disable or enable at any time. On the other side, the `ISSUES` report does not include methods that are not executed by the test suite.
