### ISSUE TITLE
Descartes stopped by invalid name for issue reporting file

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/pitest-descartes#111]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: Descartes 1.2.5, PIT 1.4.7
- **Execution Environment**: Windows 10
- **Reporter**: lars.thomas.boye@tellu.no

#### Description
Descartes stopped with the following error. It seems the problem is the extremely long file name matching the method signature, when reporting an issue (was configured to report issues). The error in Norwegian says its a syntax error with the file name/path.

[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.7:mutationCoverage (default-cli) on project core: Execution default-cli of goal org.pitest:pitest-maven:1.4.7:mutationCoverage failed: F:\Dev\tellu-github\core\target\pit-reports\201909251431\issues\no.tellu.findit.services.cassandra.ActivityLogServiceImpl\log(java.lang.String, java.lang.Long, java.lang.Long, no.tellu.findit.services.cassandra.ActivityLogItemType, no.tellu.findit.services.cassandra.HierarchyLevel, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.util.List).html (Filnavnet, mappenavnet eller volumnavnesyntaksen er feil)
[ERROR]
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : Java HotSpot(TM) 64-Bit Server VM
[ERROR] Vendor : Oracle Corporation
[ERROR] Version : 25.172-b11
[ERROR] Uptime : 489752
[ERROR] Input ->
[ERROR]  1 : -Djavax.xml.accessExternalSchema=all
[ERROR]  2 : -Dclassworlds.conf=C:/Dev/apache-maven-3.5.4/bin/m2.conf
[ERROR]  3 : -Dmaven.home=C:/Dev/apache-maven-3.5.4
[ERROR]  4 : -Dlibrary.jansi.path=C:/Dev/apache-maven-3.5.4/lib/jansi-native
[ERROR]  5 : -Dmaven.multiModuleProjectDirectory=F:/Dev/tellu-github/core
[ERROR] BootClassPathSupported : true

**Comment by oscarlvp** [comment]
This issue has been reported in #104 as it has been already solved. The next release will not have this issue.
