### ISSUE TITLE
NPE in pitest, when null value in plugin configuration (eg. undefined env variable)

### ISSUE THREAD

**Issue by gibello** [STAMP-project/pitest-descartes#116]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [pitest-descartes]
- **Execution Environment**: [Ubuntu 18.04]
- **Reporter**: [Pierre-Yves Gibello, pyg@ow2.org]

#### Description

If a null value is set in pluginConfiguration, pitest throws a NPE.

The explanation is deep in the code of pitest: line 323 in
https://github.com/hcoles/pitest/blob/master/pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java

Hashtable's putAll() method returns a NPE is there is a null value in the map.

And this may happen, for example if we set a value using an undefined environment variable:

```
<pluginConfiguration>
    <nullValue>${env.NULL_VALUE}</nullValue>
</pluginConfiguration>
```

So... you have to check that no null value is inserted, prior to calling pitest !

Root exception follows:

```
Caused by: java.lang.NullPointerException
    at java.util.Hashtable.put (Hashtable.java:460)
    at java.util.Hashtable.putAll (Hashtable.java:524)
    at org.pitest.maven.MojoToReportOptionsConverter.createPluginProperties (MojoToReportOptionsConverter.java:323)
    at org.pitest.maven.MojoToReportOptionsConverter.parseReportOptions (MojoToReportOptionsConverter.java:148)
    at org.pitest.maven.MojoToReportOptionsConverter.convert (MojoToReportOptionsConverter.java:81)
```

**Comment by oscarlvp** [comment]
> The explanation is deep in the code of pitest: line 323 in
https://github.com/hcoles/pitest/blob/master/pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java

So, this seems to be a PIT issue. Shouldn't it be better reported in their tracker?

**Comment by gibello** [comment]
No, it is not really a PIT issue.
They expect hash maps with no null value inside. A hash value set to null has no sense (at least to pit... but probably no sense at all wrt configuration).
What you should do is cleanup the map prior to passing it to PIT (removing all null values), and it will work.

**Comment by oscarlvp** [comment]
If I remember well, Descartes does not have access to this map. This happens when PIT converts the configuration written in the `pom.xml` to an object. Descartes does not enter in this process. It gets the configuration processed by PIT, so, it does not have a way to clean it, I guess.

**Comment by gibello** [comment]
Ok, I will investigate this (maybe with just PIT maven plugin, and a empty env variable in config ? It can be a PIT bug, indeed).
Thanks !
