### ISSUE TITLE
False positives while using Robolectric/Android

### ISSUE THREAD

**Issue by Kvarnefalk** [STAMP-project/pitest-descartes#133]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: random
- **Severity**: minor
- **Tool/Service/Component**: 1.2.5
- **Execution Environment**: Android using RobolectricTestRunner
- **Reporter**: John Kvarnefalk johnkv@kth.se

#### Description
Currently doing my Master thesis evaluating Descartes in CI.

I am running Descartes in the CI system on a large Android application to figure out if methods are pseudo-tested before merging them into master. Unfortunately, I am seeing a quite large amount of false positives being reported by the tooling. I do not now if this is related to Descartes or PITest since it's hard to find and create a reproduction. The issue comes up on some of the methods.

I had an issue with Robolectric earlier where PITest was mutating the code via instrumentation and Robolectric was loading the code from disc. I did a workaround for this where I basically wrote the mutated code to disc. This fixed some of the errors. However, some errors still remain. I have created an issue on the PITest repo with the first of this errors which I fixed with writing to disc. The author proposed an interesting mitigation other than my solution where we instrument how Robolectric is loading classes. Not sure if there are any straightforward ways of doing this though.

https://github.com/hcoles/pitest/issues/744

Feel free to reach out over email or here. I am aware this is a bit vague, but probably something that is good to be aware of!

**Comment by oscarlvp** [comment]
Is it possible to create a minimal example that has the issue or at least to have more information about these false positives, like types of methods, how the mocks are being used and so?

**Comment by oscarlvp** [comment]
Would it be possible to know, at least the version of Roboelectric and other frameworks and libraries in use?

**Comment by Kvarnefalk** [comment]
It's really hard to know what is wrong here. To be honest I think that my fix to PITest could be problematic as well. I don't necessarily think it's Descartes that is wrong. My patched version of PITest is here: https://github.com/Kvarnefalk/pitest

The robolectric version is 4.4 and pitest is my own version

**Comment by oscarlvp** [comment]
@Kvarnefalk it would be great if you can write a minimal class and a minimal test class that represent one of the false positives you are having. Is it possible to share the `JSON` report generated by Descartes and point out the problematic methods? You can share it via email or we can even discuss it directly.

**Comment by Kvarnefalk** [comment]
Let me see what I can do. I'll try to create a repro during the week. Fingers crossed
