### ISSUE TITLE
add support for TestNG

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/pitest-descartes#137]
Some open-source packages use TestNG and they are interesting for us (@Deee92 @gluckzhang @bbaudry  @monperrus).

@oscarlvp what are the required changes to have Descartes work with TestNG?

**Comment by oscarlvp** [comment]
https://pitest.org/quickstart/maven/#testplugin

**Comment by monperrus** [comment]
Thanks Oscar. @gluckzhang we should be able to run Descartes on TTorrent

**Comment by gluckzhang** [comment]
Thanks @monperrus and @oscarlvp ! Indeed, after specifying the `testPlugin` in the configurations, it worked with TTorrent perfectly :)

**Comment by monperrus** [comment]
cool! a PR to document this in the README would be super nice :)

**Comment by gluckzhang** [comment]
@monperrus yep. I just created a PR (#138) about adding this into the README :)
