### ISSUE TITLE
only mutate methods larger than a given size

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/pitest-descartes#141]
In order to break the build when a pseudo-method exists, we need to filter trivial cases.

For this we add support be able to only mutate methods larger than a configurable given size (say 5 lines)

**Comment by oscarlvp** [comment]
Done. See ee2b15816ed283c97cc980dc3bfecbc39755460b
To appear in 1.3

**Comment by monperrus** [comment]
Nice, thanks a lot.
