### ISSUE TITLE
running Descartes without modifying the pom.xml?

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/pitest-descartes#143]
Today, using Descartes requires to modify the pom.xml.

Would it be possible to run Descartes without changing a single line in the pom?

```
git clone https://github.com/foo/bar/
cd bar
mvn org.XXXXX:descartes
```

**Comment by oscarlvp** [comment]
PitMP does that in that exact same way. There is no need to modify the pom.

**Comment by monperrus** [comment]
For the record, per the documentation of PitMP

    mvn eu.stamp-project:pitmp-maven-plugin:descartesmvn eu.stamp-project:pitmp-maven-plugin:descartes

**Comment by monperrus** [comment]
No success so far, see https://github.com/STAMP-project/pitmp-maven-plugin/issues/53
