### ISSUE TITLE
Does not work with pitest 1.7.0

### ISSUE THREAD

**Issue by swierszczu4j** [STAMP-project/pitest-descartes#145]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crush
- **Tool/Service/Component**: pitest:1.7.0, descartes:1.3.1
- **Execution Environment**: Ubuntu 20.04

#### Description
After recent upgrade of the pitest from 1.6.9 to 1.7.0 descartes mutation engine crushes - is not able to start analysis. Change log in PIT, suggest a breaking change in internals that might affect 3-party libs.

#### Steps to reproduce
Just run `mvn org.pitest:pitest-maven:mutationCoverage` with newest (1.7.0) PIT.

You will get this:
_Execution default-cli of goal org.pitest:pitest-maven:1.7.0:mutationCoverage failed: A required class was missing while executing org.pitest:pitest-maven:1.7.0:mutationCoverage: org/pitest/mutationtest/engine/MethodName_

**Comment by oscarlvp** [comment]
Thank you for reporting this issue.
A new compatible version should be release in the upcoming days.

**Comment by swierszczu4j** [comment]
Thank U ;)

**Comment by swierszczu4j** [comment]
Hello! @oscarlvp any information, when it comes to ETA of the fix?

**Comment by oscarlvp** [comment]
@swierszczu4j 
The new release should solve the problem. Otherwise let me know.

**Comment by swierszczu4j** [comment]
Just for the record - pitest 1.7.0 with descartes 1.3.2 works like a charm! Thanks @oscarlvp one more time!
