### ISSUE TITLE
Pitest not working and throwing  module java.base does not "opens java.util"

### ISSUE THREAD

**Issue by milan-15697** [STAMP-project/pitest-descartes#148]
#### Characteristics
- **Issue Type**: [bug, feature, test report]
- **Reproducibility**: [always, sometimes, random]
- **Severity**: [feature, minor, major, crash, block]
- **Tool/Service/Component**: [name, version]
- **Execution Environment**: [platform, OS, etc]
- **Reporter**: [name, mail]

#### Description

[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @1e3ff233
[ERROR] -> [Help 1]

#### Steps to reproduce
    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.2.0</version>
            </plugin>
        </plugins>
    </build>

 mvn clean org.pitest:pitest-maven:mutationCoverage

#### [Help on issue template](https://github.com/STAMP-project/pitest-descartes/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by oscarlvp** [comment]
Thank you for opening this bug. Are you trying to run PIT on the Descartes repository?
The version of PIT you have in the snippet is quite old. Have you tried with a more recent version?
