### ISSUE TITLE
Running Descartes-PITest in Supersede DM Optimizer component generates mutations but no tests are executed.

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/pitest-descartes#16]
**Issue Type**: possible bug/misuse
**Description**: I am testing Descartes PITest in one Atos use case target projects: Supersede, and concretely in the DM Optimizer component, which is a Maven configured project, which contains 7 tests passsed by issueing mvn test in command line.
Descartes PITEST was configured in pom.xml following instructions given in Descartes GitHub readme.md. Descartes was obtained from Github, by cloning the repository, installed after mvn compile test install. As a summary of results, this is a snippet of Descartes output:

`Generated 264 mutations Killed 0 (0%)
Ran 0 tests (0 tests per mutation)`

See Steps to Reproduce section for further details.
**Reproducibility**: always
**Severity**: major
**Tool**: Descartes PITest, version 28/08/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
Descartes was tested in one component, DM Optimizer, of the Supersede Dynamic Adaptation framework. To get this framework:
`git clone https://github.com/supersede-project/dyn_adapt.git -b descartes`
Then, build the framework components (it requires a Linux OS):
`cd dyn_adpt;./buildAll.sh`
Then, go to the DM optimizer project:
`cd DM/components/eu.supersede.dynadapt.dm.optimizer/`
An execute Descartes:
`mvn org.pitest:pitest-maven:mutationCoverage`
**Files**:
I attach the full log of executing Descartes:
[Descartes_PIT_MutationCoverage_Supersede_DM_Optimizer_Maven.txt](https://github.com/STAMP-project/pitest-descartes/files/1255926/Descartes_PIT_MutationCoverage_Supersede_DM_Optimizer_Maven.txt)
I also attach the log of executing the DM Optimizer test, showing 7 test executed:
[Supersede_DM_Optimizer_Maven_Test.txt](https://github.com/STAMP-project/pitest-descartes/files/1255932/Supersede_DM_Optimizer_Maven_Test.txt)
**Relationships**: None
**Reporter**: Yosu Gorroñogoitia <jesus.gorronogoitia@atos.net>

**Comment by oscarlvp** [comment]
I've tried to reproduce the error but I'm getting build failures for some projects such as Adapter Service and ServiceCompositionEnactor. Do I need to include any specific package repository?

**Comment by jesus-gorronogoitia** [comment]
Hi Oscar, 
follow these steps to compile the module from a clean repository copy:
`git clone https://github.com/supersede-project/dyn_adapt.git -b descartes`
`cd dyn_adpt;./buildEclipseDependencies.sh`
`cd DM/components/eu.supersede.dynadapt.dm.optimizer/;./installGPLibDependency.sh;mvn clean package -Dmaven.test.skip=true`

I've tested these steps with a clean copy of above Supersede repository and also a clean copy of my local Maven repository, not facing any compilation error, but I fixed the pom.xml because former dependencies are not anymore available in Eclipse p2 Maven repositories.
