### ISSUE TITLE
Improve efficiency

### ISSUE THREAD

**Issue by oscarlvp** [STAMP-project/pitest-descartes#23]
Even when Descartes is several times faster than the default PIT engine it would be nice to improve the efficiency of the whole mutation analysis for practical use in regular development cycles.

**Comment by vmassol** [comment]
Note that this issue was raised as a result of the workshop I did with Oscar on XWiki, see my blog post at http://massol.myxwiki.org/xwiki/bin/view/Blog/MutationTestingDescartes

**Comment by oscarlvp** [comment]
This is more suited for PIT.

**Comment by vmassol** [comment]
So I guess you're saying that the performance is not going to be improved (since you're not working on PIT). That's an issue for using Descartes in real life projects.
