### ISSUE TITLE
run descartes only the code changed in last commit  / PR 

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/pitest-descartes#24]
For sake of performance, it is interesting run descartes only the code changed in last commit  / PR.

Related to Pit feature
[#132 - Allow analysis of only files touched in last commit](https://github.com/hcoles/pitest/issues/132)

**Comment by oscarlvp** [comment]
The [scmMutationCoverage goal](http://pitest.org/quickstart/maven/#scmmutationcoverage-goal) should provide this functionality, though it hasn't been tested with Descartes as mutation engine.

**Comment by monperrus** [comment]
Thanks for your fast answer. Could you make a first pilot test?

**Comment by monperrus** [comment]
just made a successful
`mvn org.pitest:pitest-maven:scmMutationCoverage`
using Descartes?

**Comment by oscarlvp** [comment]
See #14.
