### ISSUE TITLE
mutationCoverage failed: Could not load requested engine descartes

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/pitest-descartes#25]
**Issue Type**: possible bug/misuse
**Description**: I've followed the [Descartes for dummies tutorial](https://github.com/nicolabertazzo/pitest-descartes/blob/descartes-for-dummies-mvn/docs/descartes-for-dummies-mvn.md)  authored by Nicola Bertazzo. However, I get a 

> Failed to execute goal org.pitest:pitest-maven:1.2.0:mutationCoverage (default-cli) on project hello_app: Execution default-cli of goal org.pitest:pitest-maven:1.2.0:mutationCoverage failed: Could not load requested engine 

after launching Descartes with: `mvn test org.pitest:pitest-maven:mutationCoverage` in dhell project.
**Reproducibility**: always
**Severity**: major
**Tool**: Descartes PITest, version 19/10/17
**Execution Environment**: Linux OpenSuse Tumbleweed, Maven version: 3.3.9, Java version: 1.8.0_102, vendor: Oracle Corporation
**Steps to reproduce**: following _Descartes for dummies_, I've cloned Descartes from the GitHub repository and installed it using `mvn install`. I confirm Descartes plugin is installed in my Maven local repository. Then, I've cloned dhell from the repository and build it with `mvn clean package`. Next, in dhell folder, I've replaced the pom.xml file with pom.xml.for_descartes. Finally, I've executed `mvn test org.pitest:pitest-maven:mutationCoverage`
**Files**: See attached the Maven output: 
[descartes_dhell_dummies_test.txt](https://github.com/STAMP-project/pitest-descartes/files/1372045/descartes_dhell_dummies_test.txt)

**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by nicolabertazzo** [comment]
I Have the same issue.
I suggest to create a git tag with a fixed version and use these version for the for dummies tutorial.

**Comment by oscarlvp** [comment]
The issues come from the two pom.xml files as they are misconfigured. 
First, in dhell-pom.xml the class and test targets were wrong.
In pom.xml.for_descartes, the dependency is not in the right place.
I've made the changes and now they can be used properly.

**Comment by jesus-gorronogoitia** [comment]
Still not working when using dhell-pom.xml, obtaining same issue reported in #25
It works now using pom.xml.for_descartes
