### ISSUE TITLE
No mutations found. This probably means there is an issue with either the supplied classpath or filters

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/pitest-descartes#26]
**Issue Type**: possible bug/misuse
**Description**: Following the [Descartes for dummies tutorial](https://github.com/nicolabertazzo/pitest-descartes/blob/descartes-for-dummies-mvn/docs/descartes-for-dummies-mvn.md) this time I use the pom.xml file provided by Niccola in his page. Appliying Descartes to dhell project this time reports:

> No mutations found. This probably means there is an issue with either the supplied classpath or filters.

**Reproducibility**: always
**Severity**: major
**Tool**: Descartes PITest, version 19/10/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**: Similar steps described in #25. The only difference is that the pom.xml file for dhell project is [this one](https://raw.githubusercontent.com/nicolabertazzo/pitest-descartes/descartes-for-dummies-mvn/docs/dhell-pom.xml)
**Files**: See Maven execution logs attached.
[descartes_dhell_dummies_test_v2.txt](https://github.com/STAMP-project/pitest-descartes/files/1372121/descartes_dhell_dummies_test_v2.txt)

**Relationships**: #25
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by oscarlvp** [comment]
Same as #25
