### ISSUE TITLE
Usability enhancement requirement: ability to specify a concrete test suite (or groups of test suites using regular expressions) as target for mutation

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/pitest-descartes#27]
**Issue Type**: required enhancement
**Description**: I've tried Descartes on [Atos Supersede IF project](https://github.com/supersede-project/integration/tree/descartes/IF/API/eu.supersede.if.api). This project contains 33 Test Suites with a high number of test cases. Few of them are not passed, but Descartes requires a green Suite.
So, passing Descartes on this project is not possible. Only by removing the tests that are not passed.
I suggest to support (as DSpot does) to specify the concrete test suite (or groups of test suites using regular expressions) as the target of Descartes mutation process.
**Reproducibility**: always
**Severity**: normal
**Tool**: Descartes PITest, version 24/10/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
Clone Atos Supersede IF project from GitHub (descartes branch):
`git clone https://github.com/supersede-project/integration.git -b descartes`
Go to IF folder:
`cd integration/IF/API/eu.supersede.if.api`
You can run one selected TestSuite, declared in pom_for_descartes.xml, namely _FeedbackRepositoryProxyTest.java_, by using Maven:
`mvn -f pom_for_descartes.xml test`
so only this test is executed by Maven.
However, if I launch Descartes, using the same test execution constraint, all available test suites are executed, but not only the one specified in the pom_for_descartes.xml
`mvn -f pom_for_descartes.xml test org.pitest:pitest-maven:mutationCoverage`
so Descartes complains that 

> Execution default-cli of goal org.pitest:pitest-maven:1.2.0:mutationCoverage failed: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.

I would expect that only the test suite specified in the pom file would be executed, as maven test does, or at least that Descartes provides a mechanism to restrict the test suite target.

This is also a way to restrict not only the mutation target within a project but also the computation time.

**Files**:
**Relationships**: 
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

I know that you can use `-DexcludedClasses=<your.test.class>`, to prevent pit to execute this specific class (replace `<your.test.class>` by the full qualified name of your test class or a regex, you can also put several qualified name/regex, separated with comma).

In DSpot, this can be configured in the property file by specifying the property: `excludedClasses=my.first.TestClass,my.second.TestClass,all.classes.of.this.package.*` 

This feature is inside pit, so descartes should have it also ( I'm not sure).

Cheers.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin,
Indeed I am using a opposite feature, the inclusion feature in the pom.xml file (e.g. pom_for_descartes.xml), so only included test suites are executed. I mentioned this in the _steps to reproduce_ section, but not made it explicitly. This is the way I restricted the test to a concrete one, in the configuration section of the maven-surefire-plugin in Maven, that works well with _mvn test_, but Descartes still complains the suite is not green:
`<includes>
		            <include>**/FeedbackRepositoryProxyTest.java</include>
		          </includes>`

**Comment by danglotb** [comment]
According to [this](https://github.com/supersede-project/integration/blob/descartes/IF/API/eu.supersede.if.api/pom_for_descartes.xml#L345), you are configuring the **maven-surefire-plugin** (`mvn test` command). However, I think **descartes** does not have the access to this configuration.  

I suggest you to explicitly filter your test in the configuration of the descartes plugin with something like:

```xml
<excludedClasses>
    <param>com.mycompany.*</param>
    <param>com.mycompany2.SpecificTestClass</param>
</excludedClasses>
```

You have also the inclusion:
```xml
<targetClasses>
    <param>com.mycompany.package.*</param>
    <param>com.mycompany.packageB.Foo*</param>
    <param>com.partner.*</param>
</targetClasses>
```

So here, we would have:
```xml
<includes>
    <include>**/FeedbackRepositoryProxyTest.java</include>
</includes>
```
for **maven-surefire-plugin** (`mvn test` command)

is equivalent to:
```xml
<targetClasses>
    <param>**/FeedbackRepositoryProxyTest.java</param>
</targetClasses>
```
for **pit / descartes** ( `mvn -f pom_for_descartes.xml test org.pitest:pitest-maven:mutationCoverage` command)

**Comment by jesus-gorronogoitia** [comment]
Merci Benjamin. I didn't see this in the Descartes Readme.md. If this is so, I suggest to add it. If this is described in another documentation available for UC testers, please, let me know. I will try your advice out.

**Comment by danglotb** [comment]
You are welcome @jesus-gorronogoitia , thank to take the time to run **descartes**! :)

You can find a lot of configuration in the [pit-test website](pitest.org/quickstart/maven/).

Cheers! Good mutants hunt!

**Comment by jesus-gorronogoitia** [comment]
Are all pit-test Maven configurations applicable to Descartes?

**Comment by oscarlvp** [comment]
As Descartes is only a PITest plugin, everything in their site also applies, except for their mutation operators. What Descartes brings is a new set of operators very different in behaviour. I think that PITest also takes into account the surefire configuration which is directly related with Maven.
