### ISSUE TITLE
Successfully applied Descartes to Atos Supersede IF project. Could you please help me to interpret the results?

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/pitest-descartes#29]
**Issue Type**: request for support
**Description**: Successfully applied Descartes to Atos Supersede IF project. Could you please help me to interpret the results? See HTML report in zip file attached.
**Reproducibility**: always
**Severity**: normal
**Tool**: Descartes PITest, version 25/10/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
N/A
**Files**:
[atos_supersede_if_descartes_report.zip](https://github.com/STAMP-project/pitest-descartes/files/1413956/atos_supersede_if_descartes_report.zip)

**Relationships**: 
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by jesus-gorronogoitia** [comment]
Wrong zip file. I will try to run Descartes again and report

**Comment by jesus-gorronogoitia** [comment]
I cannot make Descartes to work, still facing Suite not green issue #28

**Comment by monperrus** [comment]
Should we change the issue title then?

**Comment by oscarlvp** [comment]
LEt me know if you have more issues on this.

**Comment by jesus-gorronogoitia** [comment]
I've pushed correct Descartes execution results, when applied to Atos Supersede IF project, in the [descartes-usecases-output](https://github.com/STAMP-project/descartes-usecases-output):
[Atos Supersede IF Descartes results for FeedbackRepositoryProxyTest Suite](url) 
I need some support to interpret the results and take decisions towards improve this test suite. Thanks

**Comment by jesus-gorronogoitia** [comment]
I've executed Descartes on a new suite, over the same project, and also for both suites combined (this is something didn't work before, maybe because a bad configuration). In the following days, I will try to extend the execution to more test suites to get a better code coverage.

[Experiment with Replan Controller Test Suite](https://github.com/STAMP-project/descartes-usecases-output/tree/master/atos/supersede/2018-03-27_11:36:59)
[Experiment with two test suites: FG Repository and Replan Controller](https://github.com/STAMP-project/descartes-usecases-output/tree/master/atos/supersede/2018-03-27_12:14:00)

**Comment by oscarlvp** [comment]
It would be nice to have the report in  a `JSON` file so it can be processed using our tools. You an do that by adding the following:
```xml
<outputFormats><value>HTML</value><value>JSON</value></outputFormats>
```
In this way you'll get both, the `HTML` and `JSON` reports.

**Comment by jesus-gorronogoitia** [comment]
New experiments with two test suites and JSON output available [here](https://github.com/STAMP-project/descartes-usecases-output/tree/master/atos/supersede/2018-03-27_14:23:16)

**Comment by jesus-gorronogoitia** [comment]
Hi Oscar, I've conducted new experiments using Descartes in Atos Supersede IF test suites, covering the wider test suite configuration I can make Descartes to work with.
See results  [here](https://github.com/STAMP-project/descartes-usecases-output/tree/master/atos/supersede/2018-04-25_16:41:19)
This folder contains:
- the [Descartes executions logs](https://github.com/STAMP-project/descartes-usecases-output/blob/master/atos/supersede/2018-04-25_16:41:19/descartes_if_2018-04-25_16:41:19.txt)
- the [runtime statistics during Descartes execution](https://github.com/STAMP-project/descartes-usecases-output/blob/master/atos/supersede/2018-04-25_16:41:19/descartes_if_stats_2018-04-25_16:41:19.txt)
- the [pom_for_descartes.xml](https://github.com/STAMP-project/descartes-usecases-output/blob/master/atos/supersede/2018-04-25_16:41:19/pom_for_descartes.xml) that was used as Descartes configuration
- the folder that contains the [Descartes/PITtest report](https://github.com/STAMP-project/descartes-usecases-output/tree/master/atos/supersede/2018-04-25_16:41:19/201804251647)

Could you please help me to correctly interpret this Descartes report, so I can take decisions, but also report on the evaluation report?
Please, let me know your availability next days to discuss about in a conference call. Thanks.

**Comment by oscarlvp** [comment]
I will generate a more human-readable report for you to read and put it on the same repository.
In the mean time you can check in the `mutations.json` file  a list of pseudo-tested methods and a list of partially-tested methods.
If  you recall from the last meeting, a pseudo-tested method is one for which no transformation was detected.
In the case of a void method, the transformation consists in removing all the instructions. If the method is non-void the body is replaced by "return x" where x is a constant of the corresponding returning type and several of these transformations are applied.
A partially-tested method is one for which some transformations were detected and others no. 
Both, `mutations.json` file and the `HTML` report contain all the transformations performed for each method and whether they were detected or not.

**Comment by jesus-gorronogoitia** [comment]
Hi Oscar, thanks.
So, the list of pseudo-tested methods will provide me help to identify mutated methods (transformed) which where not detected my test suite, so I should improve them in order to reduce the entries in this lists. Is there the link between pseudo-tested methods and test suites (methods), so I can identify easily the associated test methods?
Will be there further assistance by Descartes, for instance suggesting strategies to improve test resilience to pseudo-testing, such as test patterns to be adopted in test design and/or oracle/assertion design?

**Comment by oscarlvp** [comment]
Actually, the same `mutations.json` contains the list of test cases related to each method.
From what we have seen there are a lot of reason that make a method pseudo-tested, it could be the assertion or the test input, or any other cause. At the moment there are no global strategies but we are working in ways to solve testing issues behind pseudo-tested methods.

**Comment by jesus-gorronogoitia** [comment]
Hi Oscar,
how can I generate a more human-readable report from the mutations.json, so I don't need to bother you?

**Comment by jesus-gorronogoitia** [comment]
Hi Oscar,
human inspection of mutations.json is quite complex, therefore discouraged for human interpretation. At this moment, I am not capable to properly interpret the HTML report for D5.5 evaluation, and that is the reason I am requested you some tutorial help, maybe in a online meeting. The interpretation of mutations.json require those tools you refer to. 
At this moment, I am blocked and I cannot move forward to evaluate the usefulness of Descartes for D5.5. Please, let me know if you can assist us within this week. Thanks a lot.

**Comment by bbaudry** [comment]
A call would definitely help in designing this human readable report
I suggest involving ENG who could assist in the development of the report genration
