### ISSUE TITLE
Improve Report to visibly show jacoco-covered code with unkilled mutants

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/pitest-descartes#35]
Right now it takes a lot of time to navigate in the PIT Report and find some valid test to improve.

Most of the time you find either:
* Mutants not killed but on code without coverage (and thus it's normal that the mutants are not killed since there are no tests ;))
* Mutants killed

What's interesting is when there are non-killed mutants but on code which has coverage (ie which has tests).

It would be nice if the report could make it simpler to identify those cases and thus make it much simpler to identify which tests should be improved.

**Comment by oscarlvp** [comment]
We can use our own reporter (see #21). This could be a good issue for PIT.
