### ISSUE TITLE
Provide a nicer error message or default values when descartes is not configured in the pom

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/pitest-descartes#37]
See https://github.com/STAMP-project/pitest-descartes/issues/36

**Comment by oscarlvp** [comment]
I don't get where is the error in the configuration. Could you specify which was the error in the POM? Descartes deals only with the mutation operators creation, the rest comes from PIT.

**Comment by vmassol** [comment]
Yes the issue is most likely with PIT and not Descartes.

>  Could you specify which was the error in the POM? 

There was just no `<configuration>` setup in the POM AFAIR?
