### ISSUE TITLE
Improve the report to indicate code that is directly exercised by tests

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/pitest-descartes#38]
Right now the following can happen: tests can exercise some code indirectly (i.e. not test this code explicitly) and descartes can then report that some mutants were not killed. However in practice this code is not tested and it's the same situation as not having tests at all as far as this code is concerned.

The really interesting cases are when unkilled mutants belong to methods that are directly called from the test methods. It would be nice to be able to show this clearly in the report to make it simpler to find hot spots to fix.

Does it make sense? :)

**Comment by bbaudry** [comment]
Yes, this makes sense. Actually, we already collect this information and we can put these mutants at the top of the list returned by Descartes

**Comment by oscarlvp** [comment]
This information can not be obtained from PIT. But we have another tool to do this. See [STAMP-project/dissector](https://github.com/STAMP-project/dissector)

**Comment by oscarlvp** [comment]
#118 is similar to this issue and provides an updated perspective.
