### ISSUE TITLE
Tellu usecase test report

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/pitest-descartes#41]
Today, 20.12.2017, I have tried Descartes on one Tellu project. Called tellulib, I selected it because it is a fairly small single-module maven project with a decent set of straight-forward unit tests which execute quickly.

I built the current version from GitHub, and used the config suggested in the readme. It ran fine.
Result: Generated 754 mutations Killed 261 (35%). Runtime was 46 seconds.

For comparison, running PIT with default config (no Descartes): Generated 2941 mutations Killed 860 (29%). Runtime 113 seconds.

**Comment by bbaudry** [comment]
Hi @ltboye, thanks for this feedback and the comparison with PIT
Please, let us know if you found interesting hints, among the live mutants, to improve the test suite
