### ISSUE TITLE
Update to  latest PIT

### ISSUE THREAD

**Issue by oscarlvp** [STAMP-project/pitest-descartes#45]
Update the project to use the latest version of PIT.

**Comment by vmassol** [comment]
Hi @oscarlvp . What's the progress on this?

I'm stuck on the xwiki project ATM waiting for this. We're moving our tests to JUnit5 and thus I need to use https://github.com/pitest/pitest-junit5-plugin (v0.4) and this requires pitest 1.3.2+

Would be great to have an ETA.

Thanks

**Comment by oscarlvp** [comment]
Hi @vmassol, it is pretty much done, but I would like to do some tests before making a release.
If everything works, then I'll have the release by the end of this week.

**Comment by oscarlvp** [comment]
Conflict has been solved. Working on #46 to include the feature in the next release.

**Comment by vmassol** [comment]
:+1:

**Comment by oscarlvp** [comment]
Now supporting PIT 1.4.0

**Comment by vmassol** [comment]
Thanks @oscarlvp ! I'll test it as soon as it's released in a maven repo :)
