### ISSUE TITLE
question: how could we create a source-code level mutation engine for Pit?

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/pitest-descartes#47]
Some mutation operators are much easier to be implemented on source code.

How could we create a source-code level mutation engine for Pit?

**Comment by oscarlvp** [comment]
PITest has been designed to target bytecode. There are other alternatives. Take a look at  [this](http://mutation-testing.org/), an alternative that includes a DSL to specify the operators.

**Comment by monperrus** [comment]
Do it mean you think it's impossible to do so with Pit?

**Comment by oscarlvp** [comment]
Well, impossible is a tough word :)
The internal design is totally oriented to bytecode. Maybe it is possible to do something but then a lot of technical issues would have to be addressed. Major seems better suited for source code.

**Comment by monperrus** [comment]
Thanks for your insight. Asked to Henry to see what he thinks pitest/issues/450
