### ISSUE TITLE
Can we run Descartes from command line without modify the pom.xml

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/pitest-descartes#48]
Hi, I am currently re-implementing **pitest-descartes** inside **DSpot**.

I would like to run the mutation analysis through maven goal (or any other tools like gradle or ant).

Currently, I use the goal `org.pitest:pitest-maven:1.3.0:mutationCoverage` and specify a bunch of options using `-Dpropery=value`. For instance, I specify the mutation engine and the mutators as follow:
`-DmutationEngines=gregor -Dmutators=ALL`.

The problem is, that I cannot do the same with **pitest-descartes**. 

I tried to specify the specific engine and mutators with:
 `-DmutationEngines=descartes -Dmutators=void,null,true,false` 
but it seems that **PIT** does not recognize the mutators:

```
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.3.0:mutationCoverage (default-cli) on project example: Execution default-cli of goal org.pitest:pitest-maven:1.3.0:mutationCoverage failed: Mutator or group void is unknown. Check PIT configuration and try again.
[ERROR] See http://pitest.org for more details.
```

Do you think it is possible to do so? It would be great, otherwise, we would have to modify the pom of the client project, which is not very convenient, (It is what it was done before...).

WDYT?

**Comment by oscarlvp** [comment]
Well, I haven't tried descartes on 1.3.0. My first guess would be to check if the descartes artifact is included in the classpath. Otherwise PIT is not able to recognise it. Try first with PIT 1.2.0 to see if it works.

**Comment by danglotb** [comment]
I does not work either.

It seems that, I cannot use `descartes` engine from command line. 

I made a type on the option of the mutation engine (I typed `-DmutationsEngines` while it is `-DmutationEngine`)

I think I'm gonna stick to the modification of the pom

Thank you

**Comment by oscarlvp** [comment]
The only thing you actually need is to put descartes in the same execution classpath as PIT.
We do this for `PitMP`.
`PitMP` depends on both, descartes and PIT. So when it executes PIT, descartes is found as a dependency in runtime.
I actually don't modify the `pom.xml` for the projects if I use `PitMP`

**Comment by danglotb** [comment]
Hi @oscarlvp 

Thank you, I'll use `PitMP` in DSpot, to execute both PIT and Descartes without modifying the pom.
