### ISSUE TITLE
Release and Deploy 0.2

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/pitest-descartes#49]
Hello, 

What do you think about a new release and a deployment on the maven repository on GH?

Cheers,

Benjamin

**Comment by oscarlvp** [comment]
I'm working on a new release targeting PIT 1.3.0 but at the moment it is on hold.
Putting it in the maven repo would be great but I've never been able to make it work on my side from the pom.xml Is it possible to upload the artifacts directly?

**Comment by danglotb** [comment]
Hi @oscarlvp 

You should be able to deploy it using `mvn deploy`. But before that, you must add to your settings your credentials:

```
<settings>xml
  <servers>
	  <server>
	    <id>github</id>
	    <username>githubUserName</username>
	    <password>githubPassWord</password>
	  </server>
  </servers>
</settings>
```

On Linux, this file is in `${HOME}/.m2/settings.xml`.

Ensure the access of this file is constraint, only should have the access, or remove your sensitive information after the deployment.

**Comment by vmassol** [comment]
This issue is really important for us (XWiki) since we cannot use Descartes for real because of this (we need a deployed version in a maven repository). Thanks!

**Comment by vmassol** [comment]
Having it work on the latest pitest (1.3.2 as of now) would be great too :)

**Comment by CaelInria** [comment]
Hi @danglotb,

I set my settings.xml file and tried "mvn deploy" (on the Descartes master) but the site goal failed.

It seems I'm facing this issue: [https://github.com/github/maven-plugins/issues/85](https://github.com/github/maven-plugins/issues/85)
I tried the work around, but it doesn't work neither.

I compared Descartes pom.xml with DSpot one, and I cannot see the difference (except local directory name to upload in the maven repository)
How did you manage to make it work ? :-)

I attached Descartes pom.xml and traces file.
[mvn_deploy.traces.txt](https://github.com/STAMP-project/pitest-descartes/files/1819903/mvn_deploy.traces.txt)
[pom.xml.txt](https://github.com/STAMP-project/pitest-descartes/files/1819904/pom.xml.txt)

**Comment by danglotb** [comment]
Hi @CaelInria 

I don't know the problem. 

Do you want I try to deploy `pitest-descartes`?

**Comment by CaelInria** [comment]
Hello Benjamin
Oui tu peux essayer, et si cela fonctionne, il faudra qu'on compare nos environnements pour voir les différences
Sinon in peut se prévoir un call la semaine prochaine ?
:-)
Caroline
Envoyé par Blue 
Le 18 mars 2018, à 21:33, Benjamin DANGLOT <notifications@github.com> a écrit:
Hi @CaelInria
I don't know the problem.
Do you want I try to deploy pitest-descartes?

**Comment by danglotb** [comment]
I discussed with @oscarlvp and he pointed me the fact that I use `mvn deploy` instead of the combo: `mvn release:prepare` and `mvn release:perform` which is a bad practice.

For now, I'm gonna try to `mvn deploy` and see what happens. The, for further deployment and especially for deployment on maven central we must use `mvn release` right?

**Comment by vmassol** [comment]
Deploy is not a release. It just deploys the snapshot which is not what is needed! :)

See the list of steps done by release:prepare and release:perform here (you'll find it has tens of steps and deploy is just one):
* http://maven.apache.org/maven-release/maven-release-plugin/examples/prepare-release.html
* http://maven.apache.org/maven-release/maven-release-plugin/examples/perform-release.html

**Comment by danglotb** [comment]
Hi, I just released the **test-runner** artifact under the groupID `eu.stamp-project` see [this](https://oss.sonatype.org/#nexus-search;quick~eu.stamp)

I suggest you the following actions in order to deploy others artifacts:

* Configure your `pom.xml` following [this](http://central.sonatype.org/pages/apache-maven.html#using-a-profile) and using the `pom.xml` of [**test-runner**](https://github.com/STAMP-project/testrunner/blob/master/pom.xml) artifact.
* Change your groupID to `eu.stamp-project`
* Create an account on [sonatype](https://issues.sonatype.org/)/[Nexus Repository](https://oss.sonatype.org) and ping me to be added to the groupID
* perform the release with: `mvn release:clean release:prepare release:perform`

**Comment by CaelInria** [comment]
@danglotb : I created an account (Cael) on https://issues.sonatype.org/
I assume I have to update my settings.xml ? ;-)

**Comment by danglotb** [comment]
Hi @CaelInria 

I just added you to deploy artifacts to this groupId (_c.f._ this [thread](https://issues.sonatype.org/browse/OSSRH-38543?filter=-2))

You will have to generate user token in [oss.sonatype.org](https://oss.sonatype.org/) (use the same credentials than on [issues.sonatype.org](https://issues.sonatype.org/)).

You should have access to user token in your profile.

then in your `setting.xml` you add:

```
 <servers>
   <server>
      <id>ossrh</id>
      <username>user-token</username>
      <password>user-passwd</password>
    </server>
   <server>
      <id>ossrh-snapshots</id>
        <username>user-token</username>
      <password>user-passwd</password>
    </server>
  </servers>
```

You can have look to  [this](http://central.sonatype.org/pages/apache-maven.html#using-a-profile) and to the `pom.xml` of [**test-runner**](https://github.com/STAMP-project/testrunner/blob/master/pom.xml) artifact to set up your own `pom.xml`.

Finally, perform the release with `mvn release:clean release:prepare release:perform`.

The prompt will ask you the current release version and the next one.

Also, you will have to sign artifacts, by setting up a pgp key, see [this](http://central.sonatype.org/pages/working-with-pgp-signatures.html).

Cheers,

**Comment by oscarlvp** [comment]
@danglotb : Please add oscarlvp to the sonatype group.

**Comment by CaelInria** [comment]
Hi @danglotb and @vmassol,

I deployed [pitmp-maven-plugin](https://github.com/STAMP-project/pitmp-maven-plugin). :)

@danglotb : Actually I used maven-gpg-plugin for GPG key.
You can update your settings.xml with:
```
    <server>
      <id>gpg.passphrase</id>
      <passphrase>your gpg passphrase</passphrase>
    </server>
```
And have a look on [pitmp-maven-plugin pom.xml](https://github.com/STAMP-project/pitmp-maven-plugin/blob/master/pom.xml).

@vmassol : Descartes is cooming.. :)

**Comment by danglotb** [comment]
Hi @oscarlvp 

You have been added to the groupID on  [sonatype](https://issues.sonatype.org/browse/OSSRH-38543?filter=-2)

**Comment by CaelInria** [comment]
Descartes 1.0 is available. :-)
