### ISSUE TITLE
@Ignore (org.junit.Ignore) is not working when used to clean a test suite. This is not a Descartes issue, but a PITest issue

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/pitest-descartes#50]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always 
- **Severity**: major 
- **Tool/Service/Component**: Descartes/PITest, version (27/03/2018, 1.2.0) 
- **Execution Environment**: Linux Opensuse Tumbleweed
- **Reporter**: Jesús Gorroñogoitia (jesus.gorronogoitia@atos.net)

#### Steps to reproduce
N/A (A concrete Supersede IF example could be provided if required)
#### Other files and URLs
N/A
#### Relationships
N/A

**Comment by oscarlvp** [comment]
Have you tried excluding the class using the `excludedClasses` item in the configuration?
This issue is related to PIT, not Descartes. It could be fixed in the latest version.

**Comment by jesus-gorronogoitia** [comment]
excludeClasses exclude classes from being mutated, but the problem here is that Descartes/PiTest first check whether or not the test suite is green by executing the tests, before mutating the code that is invoked in those tests. mvn test works well, because it ignores the tests marked with @ignore annotation, but it seems PITest does not ignore those tests, which fail, so the test suite is marked as not green.  
I tried with excludeClasses and excludeTests, but as far as I remember, they didn't work. Nonetheless, I will double check, before confirming.

**Comment by jesus-gorronogoitia** [comment]
I will try it out then.

**Comment by jesus-gorronogoitia** [comment]
The problem is not to exclude a class or test suite, but to exclude a concrete test method: @Test (org.junit.test). If I use excludedClasses, I will exclude the entire suite (the test class), but I need just to exclude a test method. In JUnit we have @Ignore annotation for that, which is ignored by PIT, but not by Maven

**Comment by oscarlvp** [comment]
Yes, it is the only way in PIT 1.2.0. However, newer versions have better filtering capabilities. For now you'll have to exclude the entire class using this mechanism.

**Comment by jesus-gorronogoitia** [comment]
Hi Oscar, 
I am resuming this issue, as I've been conduction additional experiments.
See results of executing Descartes on Atos Supersede IF test suites [here](https://github.com/STAMP-project/descartes-usecases-output/tree/master/atos/supersede/2018-04-25_16:10:44)

In this experiments we use the entire IF test suites, which are green. However, Descates (PITest) complains of different test suites that did not pass without mutation. 

> -\|/-4:19:15 PM PIT >> SEVERE : Description [testClass=eu.supersede.integration.api.datastore.proxies.test.FEDataStoreProxyTest, name=eu.supersede.integration.api.datastore.proxies.test.FEDataStoreProxyTest] did not pass without mutation.
> \4:19:15 PM PIT >> SEVERE : Description [testClass=eu.supersede.integration.api.datastore.proxies.test.IFDataStoreProxyTest, name=eu.supersede.integration.api.datastore.proxies.test.IFDataStoreProxyTest] did not pass without mutation.
> |/-\|/-\|/-\|4:21:55 PM PIT >> SEVERE : Description [testClass=eu.supersede.integration.api.pubsub.test.AdaptationAlertPubSubTest, name=testPublishAdaptionAlertMessage(eu.supersede.integration.api.pubsub.test.AdaptationAlertPubSubTest)] did not pass without mutation.
> /4:21:55 PM PIT >> SEVERE : Description [testClass=eu.supersede.integration.api.pubsub.test.AlertPubSubTest, name=testPublishAlertMessage(eu.supersede.integration.api.pubsub.test.AlertPubSubTest)] did not pass without mutation.
> -\4:21:55 PM PIT >> SEVERE : Description [testClass=eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest, name=testPublishEvolutionAlertMessage(eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest)] did not pass without mutation.
> |4:21:55 PM PIT >> SEVERE : Description [testClass=eu.supersede.integration.api.pubsub.test.PubSubTest, name=testPublishTextMessage(eu.supersede.integration.api.pubsub.test.PubSubTest)] did not pass without mutation.
> /-\|/-4:22:12 PM PIT >> SEVERE : Description [testClass=eu.supersede.integration.federation.test.IFSupersedeFederationTest, name=eu.supersede.integration.federation.test.IFSupersedeFederationTest] did not pass without mutation.

However, lines before in the logs, Descarte/PITest informs that all tests were passed:

> [WARNING] Tests run: 161, Failures: 0, Errors: 0, Skipped: 20

Following your advice, I try to use <excludeClasses> PITest configuration to exclude conflicting classes in the [pom_for_descartes.xml](https://github.com/STAMP-project/descartes-usecases-output/blob/master/atos/supersede/2018-04-25_16:10:44/pom_for_descartes.xml) but this didn't work:
```
<excludeClasses>
<param>eu.supersede.integration.api.adaptation.dashboard.proxies.test.*</param>
<param>eu.supersede.integration.api.adaptation.proxies.test.*</param>
<param>eu.supersede.integration.federation.test.IFSupersedeFederationTest</param>
<param>eu.supersede.integration.api.datastore.proxies.test.FEDataStoreProxyTest</param>
<param>eu.supersede.integration.api.datastore.proxies.test.IFDataStoreProxyTest</param>
<param>eu.supersede.integration.api.dm.proxies.test.DMOptimizerProxyTest</param>
<param>eu.supersede.integration.api.pubsub.test.AdaptationAlertPubSubTest</param>
<param>eu.supersede.integration.api.pubsub.test.AlertPubSubTest</param>
<param>eu.supersede.integration.api.pubsub.test.EvolutionAlertPubSubTest</param>
<param>eu.supersede.integration.api.pubsub.test.PubSubTest</param>
</excludeClasses>
```

**Comment by oscarlvp** [comment]
Please check if the issue with `@Ignore` persists in the latest PITest version.

**Comment by oscarlvp** [comment]
Dos this issue still exist? Check that `excludedClasses` tag is used instead of `excludeClasses`.

**Comment by jesus-gorronogoitia** [comment]
Hi Oscar, excludedClasses worked. I haven't checked yet the @Ignore issue with latest Descartes version that uses PITest 1.3. I will, but nonetheless I will close this issue.
