### ISSUE TITLE
Unstable mutation coverage percentages

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/pitest-descartes#52]
When I run pitest/descartes on some xwiki modules, I get different percentage values across runs. for example I had 69% of xwiki-commons-crypto-common and I've set the build to fail if it gets below that values.

Without making any change to that module when I ran it today, the build failed with:

`xwiki-commons-crypto-common: Mutation score of 68 is below threshold of 69`

It's important that the number be stable. Any idea what could cause this?

**Comment by oscarlvp** [comment]
Can you share the report files? It would be nice to have them in `JSON` or `XML` format to run some analysis and verify this issue.

**Comment by vmassol** [comment]
The problem is that I don't have the report generating the score of 68 anymore. Here's a zip with the pitest output for the 69 threshold: https://up1.xwikisas.com/#uv-_aed_swRVwHfFD3iRmg

Thx

**Comment by oscarlvp** [comment]
The discussion about this issue has been ported to #62
