### ISSUE TITLE
Problem with gpg after the instalation of Descartes in Windows 7

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/pitest-descartes#57]
#### Characteristics

- **Issue Type**: possible bug

- **Reproducibility**:  always

- **Severity**: major

- **Tool/Service/Component**: pitest-descartes

- **Execution Environment**: Windows 7 Enterprise

- **Reporters**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net
& Ricardo José Tejada ricardo-jose.tejadagarcia@atos.net

#### Description

An exception is thrown when running the tests after the instalation of Descartes because gpg.exe is not found.

"Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project descartes: 
Unable to execute gpg command: Error while executing process. Cannot run program "gpg.exe": CreateProcess error=2"

#### Steps to reproduce 

Follow the  instructions to install Descartes, after "mvn install" the exception is thrown when running the tests

#### Other files and URLs

DescartesInstalationTestsProblem.txt

#### [Help on issue template](https://github.com/STAMP-project/pitest-descartes/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md
[DescartesInstalationTestsProblem.txt](https://github.com/STAMP-project/pitest-descartes/files/1894047/DescartesInstalationTestsProblem.txt)

**Comment by jesus-gorronogoitia** [comment]
Hi @oscarlvp After new Descartes upgrade (pulling the repository) it seems the building and installation of Descartes requires a proper installation and configuration of GPG (a secret key is required), so Descartes installation fails:

> [INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ descartes ---
> gpg: no default secret key: No secret key
> gpg: signing failed: No secret key
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 6.557 s
> [INFO] Finished at: 2018-04-10T15:22:40+02:00
> [INFO] Final Memory: 25M/310M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project descartes: Exit code: 2 -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Could you please update documentation, guiding us to sort this problem out? Thanks.

**Comment by jesus-gorronogoitia** [comment]
Easy to solve, I just needed to set up a key for gpg using 
`gpg --gen-key`

http://wooledge.org/~greg/crypto/node41.html

**Comment by oscarlvp** [comment]
Hi,

Anyways we need to look at this closer. Even when it is easy to fix, the gpg key should be needed only to release and deploy the project. 

Thanks for reporting this.

**Comment by oscarlvp** [comment]
Plugins needed for deploy and release are now specified in a dedicated profile. This solves the issue.
