### ISSUE TITLE
Build fails with native Java method

### ISSUE THREAD

**Issue by arnobl** [STAMP-project/pitest-descartes#63]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: 1.2.1
- **Execution Environment**: linux

#### Description

When analysing code that contains a native Java method, Descartes analysis fails:

```Java
public final class Algorithm {
    private Algorithm() {
        super();
    }

    public static native int foo(final int arg);
}
```

I do not have this problem using Pitest without Descartes.

#### Steps to reproduce

Add the above-mentioned code in a Java project and launch the Descartes maven analysis.

**Comment by oscarlvp** [comment]
Thanks for reporting the issue!
 It has been solved in commit 10ad17 and the fix will be included in the next release.
