### ISSUE TITLE
Implement a maven mojo to fail the build if there are pseudo-tested and/or partially tested methods

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/pitest-descartes#66]
This is similar to #22 but not quite. 

The idea here is to fail the build if there are pseudo tested and/or partially tested methods (this needs to be configurable).

Also we should be able to exclude some methods that are "false positives" that the developers don't want to fix, and we should be able to provide an explanation.

e.g.

```
<excludes>
  <exclude>
    <method>...
    <explanation>...
```

**Comment by oscarlvp** [comment]
We'll probably need to create a new Maven plugin to provide specialized goals for this issue and #22. The plugin should accept the custom configuration suggested in this issue. This will also solve the problem that, with PIT, one can not disable mutation in specific methods, just classes.

**Comment by oscarlvp** [comment]
Should we transfer this issue to PitMP?

**Comment by oscarlvp** [comment]
This issue has been resolved in [PitMP](https://github.com/STAMP-project/pitmp-maven-plugin)
