### ISSUE TITLE
Got "No mutation found" when executing it on xwiki-platform-rendering-macro-python

### ISSUE THREAD

**Issue by surli** [STAMP-project/pitest-descartes#72]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: [xwiki-platform-rendering-macro-python](https://github.com/xwiki/xwiki-platform/tree/master/xwiki-platform-core/xwiki-platform-rendering/xwiki-platform-rendering-macros/xwiki-platform-rendering-macro-python)
- **Execution Environment**: linux, JDK8

#### Description

We obtain the following error when running pit/descartes:
> [ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.0:mutationCoverage (pitest-check) on project xwiki-platform-rendering-macro-python: Execution pitest-check of goal org.pitest:pitest-maven:1.4.0:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
[ERROR] See http://pitest.org for more details.

PIT FAQ suggest it could be:
  - incorrect classpath: but we use standard paths
  - incorrect filters: we use descartes config
  - incorrect mutable code path: not sure what it means

Any idea? It currently prevents us to execute descartes on the whole project.

**Comment by oscarlvp** [comment]
From what I see in the code, this module has only one test class with a custom test runner. PIT is not able to handle these cases. Moreover, this module contains only one class in the main code which only declares a constructor. Descartes does not mutate constructors. I would recommend to skip the module from the analysis. you can use `<skip>true</skip>` in the PIT's configuration for this module.

**Comment by surli** [comment]
Reopening it after discussing with @vmassol 
Actually we agree that pit cannot mutate the constructor, but then it shouldn't fail the build only marked it at skipped, no?

**Comment by oscarlvp** [comment]
There is actually a configuration parameter to tell PIT whether it has to fail when no mutation is found.
Take a look at this link [http://pitest.org/quickstart/maven/#failwhennomutations](http://pitest.org/quickstart/maven/failwhennomutations).

**Comment by surli** [comment]
Thanks @oscarlvp!

**Comment by oscarlvp** [comment]
De rien :)
