### ISSUE TITLE
About reproducibility of mutation scores

### ISSUE THREAD

**Issue by surli** [STAMP-project/pitest-descartes#74]
We try using at xwiki a mutation score threshold to avoid a regression in our mutation score. However it seems that the mutation score changes randomly. Until then I assumed it was because of the timeouts: so first, could you confirm that the timeouts might impact the mutation scrore? Can we guess how much it can impact it? The underlined question is: can we rely on the threshold if the timeouts might randomly change it?

Now the second point is, that when running pit/descartes on two different machines, I got two different mutation score, but the logs are displaying 0 timeouts: 

```
================================================================================
- Statistics
================================================================================
>> Generated 45 mutations Killed 10 (22%)
>> Ran 12 tests (0.27 tests per mutation)
================================================================================
- Mutators
================================================================================
> ""
>> Generated 9 Killed 1 (11%)
> KILLED 1 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 8 
--------------------------------------------------------------------------------
> "A"
>> Generated 9 Killed 1 (11%)
> KILLED 1 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 8 
--------------------------------------------------------------------------------
> void
>> Generated 3 Killed 2 (67%)
> KILLED 2 SURVIVED 1 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------
> null
>> Generated 18 Killed 5 (28%)
> KILLED 5 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 13 
--------------------------------------------------------------------------------
> false
>> Generated 3 Killed 1 (33%)
> KILLED 1 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 2 
--------------------------------------------------------------------------------
> true
>> Generated 3 Killed 0 (0%)
> KILLED 0 SURVIVED 1 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 2 
--------------------------------------------------------------------------------
[...]
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.0:mutationCoverage (pitest-check) on project xwiki-platform-webjars-api: Mutation score of 22 is below threshold of 24 -> [Help 1]
```

I checked and apparently we don't use the exact same minor version of Java (Oracle JDK 1.8.0_162 vs Oracle JDK 1.8.0_121). Do you think it might impact the threshold like that?
Any other idea that could impact it?

**Comment by oscarlvp** [comment]
By default, PIT will multiply the timeout factor by 2.5. This can also be configured.
As for the machines, I'm not sure. Could you post the output that produces a different score? What I would like to see is if the same mutants are being killed or not, and which are the mutants that might be affecting the score.

**Comment by surli** [comment]
It looks like a duplicate indeed. And as I'm investigated more in the problem, it looks like more something I did not investigate on my side and not a bug in PIT. Closing it for now then.
