### ISSUE TITLE
Running mutationCoverage fails with Pitest 1.4.3

### ISSUE THREAD

**Issue by rubenlop88** [STAMP-project/pitest-descartes#89]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**:
- **Execution Environment**: MacOS
- **Reporter**: Ruben Lopez, rubenlop88@gmail.com

#### Description

Running mutationCoverage fails with Pitest 1.4.3

> [ERROR] Failed to execute goal org.pitest:pitest-maven:1.4.3:mutationCoverage (default) on project zen: Execution default of goal org.pitest:pitest-maven:1.4.3:mutationCoverage failed: An API incompatibility was encountered while executing org.pitest:pitest-maven:1.4.3:mutationCoverage: java.lang.NoSuchMethodError: org.pitest.mutationtest.MutationStatusTestPair.<init>(ILorg/pitest/mutationtest/DetectionStatus;Ljava/util/List;Ljava/util/List;)V

#### Steps to reproduce

Follow instructions in https://github.com/STAMP-project/pitest-descartes#quick-start-with-maven replacing the pitest version.

**Comment by oscarlvp** [comment]
Thanks for reporting!
This issue should be solved with the newer version.
You can try it by using PITest 1.4.3 and Descartes 1.2.5-SNAPSHOT, which is available from Sonatype.

**Comment by oscarlvp** [comment]
Solved in de513f4
