### ISSUE TITLE
Deploy pitest-descartes

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/pitest-descartes#9]
Hello,

I suggest to deploy pitest-descartes on the [stamp-maven-repository](https://github.com/STAMP-project/stamp-maven-repository)

Do you agree to do so?

Thank.

**Comment by monperrus** [comment]
+1 it would ease the deployment of DSpot

**Comment by vmassol** [comment]
+1 pretty please. Without this I cannot use descartes on the xwiki project easily (I'd need to deploy it on our custom maven repo which we really try to avoid). Thanks :)

**Comment by vmassol** [comment]
Actually just noticed that version 0.1 has been deployed there. Any chance of having version 0.2 too (since that's the on I'd like to use)? Even better would to get a more recent release (if changes have been made since then to descartes).
