### ISSUE TITLE
Problem understanding a lowered mutation score

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/pitest-descartes#91]
Hi, on XWiki our build just failed because of a lowered mutation score.

Indeed we added a new default method to an interface (without adding any test):

```
    default List<String> getGroup()
    {
        return Collections.emptyList();
    }
```

When executing descartes we see:

![yjgzegeghkyjkkddkbfsxabc](https://user-images.githubusercontent.com/628267/49076413-3de0cb00-f239-11e8-92cd-a3e3e02fe924.png)

And in issues.html we don't see it:

![ioqgnanrvwggxubffadzunyv](https://user-images.githubusercontent.com/628267/49076427-46390600-f239-11e8-9ab5-70337809ea97.png)

Any idea why this is not visible in the pseudo tested/partially tested list? This seems like a pseudo tested one (ie. whatever the return value the tests don't catch it), no?

Thanks

**Comment by oscarlvp** [comment]
The default method is not covered and therefore not partially-tested or pseudo-tested.
By definition, a method is classified as pseudo-tested or partially-tested if it is **covered** by at least one test case and no transformation was detected (pseudo) or some transformations were detected (partially).
