### ISSUE TITLE
Descartes on Seedstack core module

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/pitest-descartes#93]
#### Characteristics
- **Issue Type**: [ test report]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Execution Environment**: [Ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org]

#### Description

When running Descartes on Seedstack module core, I have the following message:
_Mutation testing requires a green suite._

In order to run Descartes, I generated first needed dependancy jars with the mvn package command in the root of the project.  
Then I run this command in the core folder: 
 mvn org.pitest:pitest-maven:mutationCoverage  -Pdescartes

I have attached my root pom (with Descartes profile) and my core module pom (with some updates compared to the initial pom). 

The mvn test is successfull with the pom in attachment.

[pom.txt](https://github.com/STAMP-project/pitest-descartes/files/2733432/pom.txt)
[pom.txt](https://github.com/STAMP-project/pitest-descartes/files/2733434/pom.txt)

Seedstack repository on github: https://github.com/seedstack/seed

#### [Help on issue template](https://github.com/STAMP-project/pitest-descartes/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by oscarlvp** [comment]
This message is generated by PIT. It means that, when PIT executed a test case to check the coverage, the test did not pass. I have seen this same issue before with different projects and different tests. It seems that, for some cases, the instrumentation done by PIT to gather the coverage breaks the test. Most of the times it is related to timeouts.
To continue with the experiments you have two options:
* Tell PIT to ignore the test in the configuration
* If the test case fails due to a timeout, increase the timeout factor used by PIT. See [here](http://pitest.org/quickstart/maven/#verbose)

**Comment by assadOW2** [comment]
Thanks @oscarlvp !

I updated the pom with those parameters:

```
<excludedTestClasses>			<param>org.seedstack.seed.core.internal.crypto.EncryptionServiceBindingFactoryTest</param>
								<param>org.seedstack.seed.core.internal.init.ProxyManagerTest</param>
								<param>org.seedstack.seed.core.ValidationIT</param>
								<param>org.seedstack.seed.core.internal.crypto.KeyPairConfigFactoryTest</param>
								<param>org.seedstack.seed.core.KeyStoreIT</param>
								<param>org.seedstack.seed.core.JndiIT</param>
								<param>org.seedstack.seed.core.IgnoreIT</param>
								<param>org.seedstack.seed.core.ExpressionLanguageIT</param>	
								<param>org.seedstack.seed.core.ExpressionLanguageHandlerIT</param>	
								<param>org.seedstack.seed.core.DiagnosticManagerIT</param>	
								<param>org.seedstack.seed.core.CryptoIT</param>	
								<param>org.seedstack.seed.core.CorePluginIT</param>	
								<param>org.seedstack.seed.core.ConfigurationProfilesIT</param>	
								<param>org.seedstack.seed.core.ConfigurationIT</param>	
								<param>org.seedstack.seed.core.CommandIT</param>	
								<param>org.seedstack.seed.core.CliIT</param>	
								
							</excludedTestClasses>

```

And it worked fine. I am going to upload results in output repository and close the issue.
