### ISSUE TITLE
Check compatibility of custom reporters with matrix execution

### ISSUE THREAD

**Issue by oscarlvp** [STAMP-project/pitest-descartes#98]
The test-mutant matrix execution may produce a list of tests that have detected a mutant instead of only one. Check that the custom reporters included in descartes can handle a list of tests in that case.

**Comment by gibello** [comment]
@oscarlvp What about that test-mutant matrix: any configuration to activate it ?
AFAIK, succeding-tests is never filled by PIT, except if using -DfullMutationMatrix=true ... But doing so, only XML reports are allowed (so forget the custom reporter).
Does Descartes provide another way of obtaining the list of succeding tests ?? Found no doc about that...
